greenlight/config/routes.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get 'health_check', to: 'health_check/health_check#index'

  # Error routes.
  match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_error', via: :all, as: :internal_error

  # Signin/Signup routes.
  get '/signin', to: 'users#signin', as: :signin
  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create', as: :create_user

  # Redirect to terms page
  match '/terms', to: 'users#terms', via: [:get, :post]

  # Admin resouces
  resources :admins, only: [:index]

  scope '/admins' do
    post '/branding', to: 'admins#branding', as: :admin_branding
    post '/coloring', to: 'admins#coloring', as: :admin_coloring
    post '/room_authentication', to: 'admins#room_authentication', as: :admin_room_authentication
    post '/coloring_lighten', to: 'admins#coloring_lighten', as: :admin_coloring_lighten
    post '/coloring_darken', to: 'admins#coloring_darken', as: :admin_coloring_darken
    post '/signup', to: 'admins#signup', as: :admin_signup
    get '/edit/:user_uid', to: 'admins#edit_user', as: :admin_edit_user
    post '/promote/:user_uid', to: 'admins#promote', as: :admin_promote
    post '/demote/:user_uid', to: 'admins#demote', as: :admin_demote
    post '/ban/:user_uid', to: 'admins#ban_user', as: :admin_ban
    post '/unban/:user_uid', to: 'admins#unban_user', as: :admin_unban
    post '/invite', to: 'admins#invite', as: :invite_user
    post '/registration_method/:method', to: 'admins#registration_method', as: :admin_change_registration
    post '/approve/:user_uid', to: 'admins#approve', as: :admin_approve
  end

  scope '/themes' do
    get '/primary', to: 'themes#index', as: :themes_primary
  end

  # Password reset resources.
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Account activation resources
  scope '/account_activations' do
    get '/', to: 'account_activations#show', as: :account_activation
    get '/edit', to: 'account_activations#edit', as: :edit_account_activation
    post '/resend', to: 'account_activations#resend', as: :resend_email
  end

  # User resources.
  scope '/u' do
    # Handles login of greenlight provider accounts.
    post '/login', to: 'sessions#create', as: :create_session

    # Log the user out of the session.
    get '/logout', to: 'sessions#destroy'

    # Account management.
    get '/:user_uid/edit', to: 'users#edit', as: :edit_user
    patch '/:user_uid/edit', to: 'users#update', as: :update_user
    delete '/:user_uid', to: 'users#destroy', as: :delete_user

    # All user recordings
    get '/:user_uid/recordings', to: 'users#recordings', as: :get_user_recordings
  end

  # Handles Omniauth authentication.
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post], as: :omniauth_session
  get '/auth/failure', to: 'sessions#omniauth_fail'

  # Room resources.
  resources :rooms, only: [:create, :show, :destroy], param: :room_uid, path: '/'

  # Extended room routes.
  scope '/:room_uid' do
    post '/', to: 'rooms#join'
    patch '/', to: 'rooms#update', as: :update_room
    post '/update_settings', to: 'rooms#update_settings'
    post '/start', to: 'rooms#start', as: :start_room
    get '/logout', to: 'rooms#logout', as: :logout_room
  end

  # Recording operations routes
  scope '/:meetingID' do
    # Manage recordings
    scope '/:record_id' do
      post '/', to: 'recordings#update_recording', as: :update_recording
      delete '/', to: 'recordings#delete_recording', as: :delete_recording
    end
  end

  root to: 'main#index'
end

greenlight/app/views/shared/admin_settings/_site_settings.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="form-group">
  <div class="row">
    <div class="col-12">
      <div class="mb-7 form-group">
        <label class="form-label"><%= t("administrator.site_settings.branding.title") %></label>
        <label class="form-label text-muted"><%= t("administrator.site_settings.branding.info") %></label>
        <div class="input-group">
          <input id="branding-url" type="text" class="form-control" value="<%= logo_image %>">
          <span class="input-group-append">
            <button id="branding-image" onclick="changeBrandingImage('<%= admin_branding_path %>')" class="btn btn-primary" type="button"><%= t("administrator.site_settings.branding.change") %></button>
          </span>
        </div>
      </div>

      <div class="form-group">
        <label class="form-label"><%= t("administrator.site_settings.color.title") %></label>
        <label class="form-label text-muted"><%= t("administrator.site_settings.color.info") %></label>
        <div class="row gutters-xs">
          <div class="col-auto">
            <input id="coloring-path" value="<%= admin_coloring_path %>" hidden>
            <input id="user-colour" value="<%= user_color %>" hidden/>
            <div class="colorinput">
              <span class="colorinput-color" style="background: <%= user_color %>;">
                <i class="p-1 fas fa-paint-brush"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

greenlight/app/views/shared/admin_settings/_users.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="form-group">
  <div class="row">
    <div class="col-12">
      <div class="table-responsive">
        <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
          <thead>
            <tr>
              <th data-header="name" data-order="<%= @order_column == "name" ? @order_direction : "none" %>">
                <%= t("administrator.users.table.name") %>
                <% if @order_column == "name" && @order_direction == "desc" %>
                 ↓
                <% elsif @order_column == "name" && @order_direction == "asc" %>
                 ↑
                <% end %>
              </th>
              <th data-header="email" data-order="<%= @order_column == "email" ? @order_direction : "none" %>">
                <%= t("administrator.users.table.username") %>
                <% if @order_column == "email" && @order_direction == "desc" %>
                 ↓
                <% elsif @order_column == "email" && @order_direction == "asc" %>
                 ↑
                <% end %>
              </th>
              <th class="text-left" data-header="provider" data-order="<%= @order_column == "provider" ? @order_direction : "none" %>">
                <%= t("administrator.users.table.authenticator") %>
                <% if @order_column == "provider" && @order_direction == "desc" %>
                 ↓
                <% elsif @order_column == "provider" && @order_direction == "asc" %>
                 ↑
                <% end %>
              </th>
              <th class="text-center">
                <%= t("administrator.users.table.role") %>
              </th>
              <th class="text-center">
              </th>
            </tr>
          </thead>
          <tbody id="users-table">
            <tr id="no_users_found" style="display: none;">
              <td colspan="7" class="text-center h4 p-6 font-weight-normal" >
                <%= t("administrator.users.table.not_found") %>
              </td>
            </tr>
            <% if @users %>
              <% @users.each do |user| %>
                <% if user != current_user %>
                  <tr data-user-uid="<%= user.uid %>">
                    <td>
                      <div><%= user.name %></div>
                      <div class="small text-muted"><%= [t("administrator.users.table.created"), ": ", user.created_at].join %></div>
                    </td>
                    <td><%= user.email && user.email != "" ? user.email : user.username%></td>
                    <td><%= user.provider %></td>
                    <td class="text-center">
                    <% roles = user.roles().pluck(:name) %>
                      <% if roles.include?("denied")%>
                        <div class="user-role btn btn-sm btn-gray-dark">
                          <%= t("roles.banned") %>
                        </div>
                      <% elsif roles.include?("super_admin") %>
                        <div class="user-role btn btn-sm btn-red">
                          <%= t("roles.super_admin") %>
                        </div>
                      <% elsif roles.include?("admin") %>
                        <div class="user-role btn btn-sm btn-yellow">
                          <%= t("roles.administrator") %>
                        </div>
                      <% else %>
                        <div class="user-role btn btn-sm btn-gray">
                          <%= t("roles.user") %>
                        </div>
                      <% end %>
                    </td>
                    <td>
                      <% unless roles.include?("super_admin") %>
                        <div class="item-action dropdown">
                          <a href="javascript:void(0)" data-toggle="dropdown" class="icon">
                            <i class="fas fa-ellipsis-v px-4"></i>
                          </a>
                          <div class="dropdown-menu dropdown-menu">
                            <% if roles.include?("denied") %>
                              <%= button_to admin_unban_path(user_uid: user.uid), class: "dropdown-item" do %>
                                <i class="dropdown-icon fas fa-lock-open"></i> <%= t("administrator.users.settings.unban") %>
                              <% end %>
                            <% else %>
                              <%= link_to admin_edit_user_path(user_uid: user.uid), class: "dropdown-item" do %>
                                <i class="dropdown-icon fas fa-user-edit"></i> <%= t("administrator.users.settings.edit") %>
                              <% end %>
                              <button class= "delete-user dropdown-item" data-toggle="modal" data-target="#deleteAccountModal">
                                <i class="dropdown-icon fas fa-user-minus"></i> <%= t("administrator.users.settings.delete") %>
                              </button>

                              <% if roles.include?("admin") %>
                                <%= button_to admin_demote_path(user_uid: user.uid), class: "dropdown-item" do %>
                                  <i class="dropdown-icon fas fa-level-down-alt"></i> <%= t("administrator.users.settings.demote") %>
                                <% end %>
                              <% elsif roles.include?("user") %>
                                <%= button_to admin_promote_path(user_uid: user.uid), class: "dropdown-item" do %>
                                  <i class="dropdown-icon fas fa-level-up-alt"></i> <%= t("administrator.users.settings.promote") %>
                                <% end %>
                              <% end %>
                              <%= button_to admin_ban_path(user_uid: user.uid), class: "dropdown-item" do %>
                                <i class="dropdown-icon fas fa-lock"></i> <%= t("administrator.users.settings.ban") %>
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            <% else %>
              <tr>
                <td colspan="7" class="text-center h4 p-6 font-weight-normal" >
                  <%= t("administrator.users.table.no_users") %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="float-right mt-4">
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>